name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "967aa1e951504aefb4f4572e478a52cf" },
  { binding = "SHARE", id = "36202120f28545e5a9a8f68cd781772b" }
]